import { createFileRoute } from "@tanstack/react-router";
import { DrawdownChart, LineSeriesChart } from "@/components/stratum/charts";
import { KeyValue, Panel, Provenance, Shell, Stat, Table } from "@/components/stratum/shell";
import { fmtInt, fmtNum, fmtPct } from "@/lib/format";
import { getExperiment } from "@/stratum/store";

export const Route = createFileRoute("/risk")({
  head: () => ({
    meta: [
      { title: "Risk Analytics — STRATUM" },
      {
        name: "description",
        content:
          "Historical and parametric VaR, CVaR, drawdown, downside deviation, beta and exposure for the simulated strategy, each with its assumptions stated.",
      },
      { property: "og:title", content: "Risk Analytics — STRATUM" },
      {
        property: "og:description",
        content: "A risk report that names its assumptions instead of hiding them behind a single number.",
      },
    ],
  }),
  component: Risk,
});

function Risk() {
  const exp = getExperiment();
  const r = exp.risk;
  const points = exp.strategy.points;
  const rolling = points.slice(-300).map((p, i, arr) => {
    const window = arr.slice(Math.max(0, i - 20), i + 1).map((x) => x.ret);
    const mean = window.reduce((a, b) => a + b, 0) / window.length;
    const variance = window.reduce((a, b) => a + (b - mean) ** 2, 0) / Math.max(1, window.length - 1);
    return { timestamp: p.timestamp, vol: Math.sqrt(variance * 252) };
  });

  return (
    <Shell
      title="Risk"
      subtitle={`Computed on ${fmtInt(r.observations)} simulated bars from ${r.periodStart} to ${r.periodEnd}.`}
      meta={<Provenance kind="backtest" note="Risk of a simulated track record" />}
    >
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Stat label="Annualised volatility" value={fmtPct(r.annualisedVolatility)} hint="Realised over the window" />
        <Stat label="Max drawdown" value={fmtPct(r.maxDrawdown)} tone="negative" hint="Worst peak-to-trough" />
        <Stat label="Historical VaR 95%" value={fmtPct(r.historicalVaR95)} tone="negative" hint="Empirical 5th percentile of daily returns" />
        <Stat label="CVaR 95%" value={fmtPct(r.cvar95)} tone="negative" hint="Mean loss conditional on breaching VaR" />
        <Stat label="Parametric VaR 95%" value={fmtPct(r.parametricVaR95)} tone="estimate" hint="Normal approximation; understates fat tails" />
        <Stat label="Historical VaR 99%" value={fmtPct(r.historicalVaR99)} tone="negative" hint="Only ~1 in 100 bars informs this estimate" />
        <Stat label="Downside deviation" value={fmtPct(r.downsideDeviation)} hint="Volatility of negative returns only" />
        <Stat label="Beta to buy & hold" value={r.beta === null ? "n/a" : fmtNum(r.beta)} hint="Sensitivity to the benchmark series" />
      </div>

      <Panel className="mt-6" title="Assumptions behind every number above" description="Generated by the risk engine, not written by hand.">
        <ul className="space-y-2 text-sm leading-relaxed text-muted-foreground">
          {r.assumptions.map((a) => (
            <li key={a}>• {a}</li>
          ))}
        </ul>
      </Panel>

      <div className="mt-4 grid gap-4 xl:grid-cols-2">
        <Panel title="Drawdown" description="The risk measure investors actually experience.">
          <DrawdownChart data={points.map((p) => ({ timestamp: p.timestamp, drawdown: p.drawdown }))} height={240} />
        </Panel>
        <Panel title="Rolling 21-bar annualised volatility" description="Volatility is not constant, so a single figure is a summary at best.">
          <LineSeriesChart
            data={rolling}
            xKey="timestamp"
            series={[{ key: "vol", label: "Rolling vol", color: "var(--color-chart-4)" }]}
            yTickFormatter={(v) => `${(v * 100).toFixed(0)}%`}
            height={240}
          />
        </Panel>
      </div>

      <div className="mt-4 grid gap-4 xl:grid-cols-2">
        <Panel title="Historical vs parametric VaR" description="The gap between the two is a direct read on tail non-normality.">
          <Table
            head={["Measure", "Value", "Method", "Reliability"]}
            rows={[
              ["VaR 95%", fmtPct(r.historicalVaR95), "Empirical quantile", "Uses ~5% of observations"],
              ["VaR 95%", fmtPct(r.parametricVaR95), "Normal (μ, σ)", "Assumes normality; understates tails"],
              ["CVaR 95%", fmtPct(r.cvar95), "Mean of the tail beyond VaR", "Coherent measure; still sample-limited"],
              ["VaR 99%", fmtPct(r.historicalVaR99), "Empirical quantile", "Very few observations; wide error"],
            ]}
          />
        </Panel>
        <Panel title="Exposure and concentration" description="Position-level risk, separate from return-level risk.">
          <KeyValue
            items={[
              ["Average gross exposure", r.averageGrossExposure === null ? "n/a" : fmtNum(r.averageGrossExposure, 2)],
              ["Annualised turnover", r.annualTurnover === null ? "n/a" : fmtNum(r.annualTurnover, 1)],
              ["Concentration (Herfindahl)", r.concentration === null ? "n/a" : fmtNum(r.concentration, 3)],
              ["Instruments traded", "1 (single-asset strategy)"],
              ["Leverage", `Capped at ${fmtNum(exp.config.backtest.maxGrossExposure, 2)}× gross`],
              ["Margin and financing", "Not modelled"],
            ]}
          />
          <p className="mt-3 text-xs text-muted-foreground">
            A Herfindahl index of 1 means all risk sits in a single position, which is exactly the case here. Treat the
            drawdown figures as the risk of one instrument, not of a diversified portfolio.
          </p>
        </Panel>
      </div>

      <Panel className="mt-4" title="Worst simulated bars" description="The observations that drive the tail statistics.">
        <Table
          head={["Timestamp", "Return", "Equity", "Drawdown", "Weight"]}
          rows={[...points]
            .sort((a, b) => a.ret - b.ret)
            .slice(0, 10)
            .map((p) => [
              p.timestamp,
              <span key={`${p.timestamp}-r`} className="text-negative">
                {fmtPct(p.ret, 3)}
              </span>,
              fmtNum(p.equity),
              fmtPct(p.drawdown),
              fmtNum(p.weight, 2),
            ])}
        />
      </Panel>
    </Shell>
  );
}
