/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SignalsRouteImport } from './routes/signals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/features': typeof FeaturesRoute
  '/market': typeof MarketRoute
  '/models': typeof ModelsRoute
  '/portfolio': typeof PortfolioRoute
  '/predictions': typeof PredictionsRoute
  '/risk': typeof RiskRoute
  '/signals': typeof SignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/features': typeof FeaturesRoute
  '/market': typeof MarketRoute
  '/models': typeof ModelsRoute
  '/portfolio': typeof PortfolioRoute
  '/predictions': typeof PredictionsRoute
  '/risk': typeof RiskRoute
  '/signals': typeof SignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/features': typeof FeaturesRoute
  '/market': typeof MarketRoute
  '/models': typeof ModelsRoute
  '/portfolio': typeof PortfolioRoute
  '/predictions': typeof PredictionsRoute
  '/risk': typeof RiskRoute
  '/signals': typeof SignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/features'
    | '/market'
    | '/models'
    | '/portfolio'
    | '/predictions'
    | '/risk'
    | '/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/features'
    | '/market'
    | '/models'
    | '/portfolio'
    | '/predictions'
    | '/risk'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/features'
    | '/market'
    | '/models'
    | '/portfolio'
    | '/predictions'
    | '/risk'
    | '/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  FeaturesRoute: typeof FeaturesRoute
  MarketRoute: typeof MarketRoute
  ModelsRoute: typeof ModelsRoute
  PortfolioRoute: typeof PortfolioRoute
  PredictionsRoute: typeof PredictionsRoute
  RiskRoute: typeof RiskRoute
  SignalsRoute: typeof SignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  FeaturesRoute: FeaturesRoute,
  MarketRoute: MarketRoute,
  ModelsRoute: ModelsRoute,
  PortfolioRoute: PortfolioRoute,
  PredictionsRoute: PredictionsRoute,
  RiskRoute: RiskRoute,
  SignalsRoute: SignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
